server:
  port: 8083

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/pagos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  group:
    aws: pagos-log-group
